# Generated by Django 3.1 on 2020-09-01 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContextRecords',
            new_name='ContextRecord',
        ),
    ]
